#                                     Digging deep with Numpy
* Two dimensional array
* checking shape, type and flatening the array
* Random, rand and randn
* Indexing and slicing the array
* Logical indexing


In [1]:
#     getting to know the array
# multidimensional array
import numpy as np
multi_array = np.array(([1,2],[3,4],[5,6]))
multi_array.ndim                         # ndim show the dimension of the query

2

In [2]:
# checking for the data type in the 2D array.
#     getting to know the array
multi_array.dtype                    # ndim show the dimension

dtype('int64')

In [3]:
# Incase we want to transform the datat type to float
transform_data = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)
transform_data

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [4]:
transform_data.shape               #represents info. on the dimensions
#. 3 represents the number of rows in a dataframe
# 2 - stands for the columns

(3, 2)

In [5]:
# Flatening the array from two dimensions to one dimension.

# ravel : is used to flaten my array, that means that it can flatten my dataset to one dimensionl

transform_data.ravel()   # we can see it has become as one dimnsion.

array([1., 2., 3., 4., 5., 6.])

### For getting the two dimentional data structures to one D, we can also use to FLATTEN function of numpy. Please check that out

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [6]:
np.random.rand(2)

array([0.59693832, 0.183052  ])

In [7]:
np.random.rand(5,5)

array([[0.56726057, 0.17224276, 0.74485682, 0.21862469, 0.89906934],
       [0.53523298, 0.64208842, 0.08704844, 0.28352561, 0.68722271],
       [0.14574383, 0.43645332, 0.53082278, 0.26721086, 0.9279939 ],
       [0.64437681, 0.36244642, 0.59400188, 0.72939435, 0.70497358],
       [0.29140658, 0.89661109, 0.2096657 , 0.11828829, 0.66567453]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [8]:
np.random.randn(2)

array([ 1.32918901, -0.6252226 ])

In [9]:
np.random.randn(5,5)

array([[-0.73341096, -0.73931221, -1.48446529,  1.13461747,  0.00310981],
       [-1.86362797, -0.06237947, -0.07963791,  0.07328417,  0.91611387],
       [-0.46651077,  0.44212488, -0.20055241,  0.6392376 , -1.16541939],
       [ 0.17612235, -0.24610816,  1.51766225, -0.01091385,  0.24518431],
       [ 1.6309771 , -0.77186474,  0.25623224,  0.66611987,  0.39283618]])

In [10]:
np.random.randint(1,100,10)

array([71, 41, 87, 21,  9,  8, 81, 33, 23, 59])

## Indexing and Slicing

In [11]:
# Accesssing Single element.
x1 = np.array([5,6,7,8,9])

In [12]:
x1[0]   #  yes at zero position 5 is present

5

In [13]:
x1[4]  # likewise at the fourth position ii is 9

9

In [14]:
# For the first time we are adding a multi-dimensional feature.
x2 = np.random.randint(10, size=(3, 4))
x2                              # items can be accessed using a comma-separated tuple of indices:

array([[8, 8, 7, 5],
       [1, 9, 5, 4],
       [7, 2, 4, 0]])

In [15]:
x2[0, 0]    # will give us the initial single position

8

In [16]:
# now let us get some middle position.
x2[1, 2]       # before comma it refers to the rows & post comma it is the column

5

In [17]:
# Please guess what shoould we write if I want the very bottom value towards left hand side.
x2[ , ]

SyntaxError: invalid syntax (<ipython-input-17-65dae64d3136>, line 2)

In [18]:
# Adding another feature of modifying the two dimensional dataset.
x2[0, 0] = 12
x2

array([[12,  8,  7,  5],
       [ 1,  9,  5,  4],
       [ 7,  2,  4,  0]])

In [ ]:
# Slicing with the numpy.  For one dimensional it is same as lists.

x = np.arange(10)
x

In [ ]:
# getting the first five elements.
x[:5]  # first five elements

In [ ]:
# If I want between index 4 and 7, what should be my syntax.
x[:]

In [ ]:
# Let us jump on to multi-dimensional aubarrays.
x2

In [ ]:
x2[:2, :3]

In [ ]:
x2[:3, ::2]  # all rows, every other column

## Logical Indexing

In [ ]:
xyz = np.array(([1,2,24,1],[33,4,85,53],[15,76,12,0]))
xyz

In [ ]:
# we are looking for the elements that are greater than 30
xyz > 30

In [ ]:
# we can also get all the elementss, if we follow like one dimensional.
xyz[xyz > 30]

# this is okey to get, but now let us focus column wise

In [ ]:
# we are focusing on one column and all the rows in that column

xyz[:, 2]

In [ ]:
# now in the above case lets see what all are greater than 30.
xyz[:, 2] > 30

In [ ]:
# In the above cell we are getting it in form of True / False. Suppose we want to know the values.
xyz[:, 2][xyz[:, 2] > 30]

### Please check out the below link for further understanding!

[tutorials on numpy](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)
