#                                     Numpy
* Why Numpy?
* Data structures of Numpy
* Demonstration of why numpy uses less memory, is fast and also convenient.
* Exploring one Dimensional array's with Numpy

Features of Numpy we should remember!

* Numpy is the fundamental package for scientific computing in python.
 * Scientific Computing is the collection of tools, techniques, and theories required to solve on a computer mathematical models of problems in Science and Engineering.
* Features of numpy array's:
 * Numpy allows vectorization
 * Is faster than the list, Numpy is based on C.
 * Array's are of single type. (Lists can accomodate all types/ numpy does one at a time)
 * Mathematical operations can be performed over an entier array.
 

In [1]:
import numpy as np
its_an_array = np.array([1,2,3])

In [2]:
its_an_array

array([1, 2, 3])

Post runing the above cell, we need to see how exactly it looks?

* - If it is looking like a list, then why should we be reading about array?

Mjorly because of the below reasons:
- less memory
- convenient
- fast

In [3]:
# Importing the required libraries.
import sys   
import numpy as np


In [4]:
#                                     Demonstrating the less memory case :-
# creating a python list                         
lists = range(5000)
print(sys.getsizeof(5) * len(lists))
# in below case the result is showing the number of bytes.

140000


In [5]:
array = np.arange(5000)
print(array.size * array.itemsize)
# array.size - is the total length of the array
# array.itemsize is the size of an element

40000


In [ ]:
#  above we can see the numbers in form of the 140000 and 40000.
# Their these values are showing the BYTES. lists are taking the 140000 Bytes and the numpy taking the 40000 bytes 

In [6]:
#                                Convenient
# In case of list when I am trying to add two elements of the list, it is concatenatng.
list1 = [1,2,3,4]
list2  = [5,6,7,8]
suming_both = list1 + list2
suming_both

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
# okey! now let us try doing any other mathematical operation over the lists.
spicy = l1 * l2
spicy

NameError: name 'l1' is not defined

In [8]:
#  now let us see doing the same functinoality over an array:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
suming_both = array1 + array2
print(suming_both)

[ 6  8 10 12]


In [9]:
# at same time, let us check for the multiplication as well.
array1 * array2 

array([ 5, 12, 21, 32])

Numpy is also fast. Please check out the link for the justification.

[How come numpy is faster than python list](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists)

In [10]:
# 
a = np.arange(10000)
%timeit a + 1  

5.64 µs ± 440 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
l = range(10000)
%timeit [i+1 for i in l] 

710 µs ± 5.94 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


[difference between the timings](https://stackoverflow.com/questions/11813999/what-do-ns-and-us-stand-for-in-timeit-result)

## One Dimensional array's with Numpy

In [12]:
# here K is list and if we wanted to go ahead with the mathematical operation, we had to loop over each element.
k = [12,3,4,8,12]


# we can see the looping that was required.
for i in k:
    print(i * 2)

24
6
8
16
24


In [13]:
# With the numpy array we can see the amount of flexibility we got:

change_k = np.array(k)

change_k * 2

array([24,  6,  8, 16, 24])

### Subsetting and slicing

In [14]:
#Subsetting and slicing is exactly like what we have done before.

# what should we write to get the first three elements.  Please help!!

change_k

array([12,  3,  4,  8, 12])

In [15]:
# if just want last two elements, then hat should we write.   Please help!!

change_k

array([12,  3,  4,  8, 12])

###  Logical Indexing or Boolean Indexing

In [16]:
# Firstly lets define a numpy array.

import numpy as np

y = np.array([24,32,67,96,33])

In [17]:
## This is how our array looks like.
y

array([24, 32, 67, 96, 33])

In [18]:
##.   now we want to check what all values are greater than 35.
y > 35

array([False, False,  True,  True, False])

In [19]:
# likewise we can also do other comparisons. e.g.

y == 33

# also we can perform other functions such as !=, >=, <= etc.

array([False, False, False, False,  True])

In [20]:
# This same information can be used for doing the subsetting. 

y[y > 33]

# here we are defining first whether y is greater than 22 and then we are putting this back in the y array. 

array([67, 96])

In [ ]:
# Going with the above logice please give the values that are equal to 44. It has to be in subsetting form

