##                                        Topics to be covered
* Vectorization in Practice
* Broadcasting
* Going ahead with few more mathematical operations


In [1]:
#                                              Vectorize implementation

import numpy as np

num = 10000000

In [2]:
a = np.random.random(num)    #array of 10 million numbers
b = np.random.random(num)     # two different arrays.

In [3]:
import time
start = time.time()
c = np.dot(a,b)
end = time.time()
print(c)
print("Verctorize  : " +  str((end -start)*1000) + 'ms')   # multiplyin by 1000 beacuse it gives in form of a nano-second

2500878.642519923
Verctorize  : 230.63993453979492ms


In [4]:
#                                           Non-vectorize implementation
start = time.time()
c =0
for i in range(num):
    c += a[i]*b[i]
end = time.time()
print(c)
print("Loop version  : " +  str((end -start)*1000) + 'ms')

2500878.642520184
Loop version  : 5401.418924331665ms


## Broadcasting : Treats arrays with different shapes during arithmetic operations.
##  the smaller array is “broadcast” across the larger array so that they have compatible shapes.

### General Broadcasting Rules
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

* they are equal, or
* one of them is 1

In [5]:
# NumPy operations are usually done on pairs of arrays on an element-by-element basis.
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [6]:
# NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints.
a = np.array([1.0, 2.0, 3.0])
b = 2.0

a * b

array([2., 4., 6.])

In [7]:
# A bit not too straight example of Broadcasting.
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

a[:, np.newaxis] + b  # we are getting the extra row at the top of the existing row. Just because of Numpy.


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

[link for exploring Broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

In [ ]:
# Number of ufunc available are:
- Arithmetic function: +,-,/,//,%,**
- Bitwise function - &,|,^,<<,>>
- Comparison Operators - <>, <=, >=, ==, !=
- Trignometry Family - np.sin, np.cos, np.tan
- Special Functions - scipy.special.* 

In [8]:
# aggregations : Are the functions which summarizes the value in an array - like min, max, mean etc.
from random import random
c = [random() for i in range(100000)]

% timeit min(c)

1.68 ms ± 71.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
c = np.array(c)

% timeit c.min()

35.4 µs ± 842 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
# Using them on multidimentional array:
M = np.random.randint(0, 10, (3,5))
M

array([[7, 5, 4, 8, 3],
       [6, 1, 4, 4, 7],
       [4, 9, 7, 2, 8]])

In [11]:
M.sum(axis = 0)   # sum of all the columns

array([17, 15, 15, 14, 18])

In [12]:
M.sum(axis = 1)       #sum of all the rows

array([27, 22, 30])

In [ ]:
Other aggregators that are used are:
np.mean()    np.max()    np.sum()    np.prod()    np.min()    np.std()    np.var()
np.any()     np.all()    np.media()  np.percentile()     np.argmin()      np.argmax()
np.nanmin()   np.nanmax()     np.nansum()